"""update env.person_in_charge

Revision ID: 75b9cbe8ad89
Revises: 3fa92102011c
Create Date: 2018-06-12 17:50:14.461163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b9cbe8ad89'
down_revision = '3fa92102011c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('env', sa.Column('person_in_charge', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_env_person_in_charge'), 'env', ['person_in_charge'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_env_person_in_charge'), table_name='env')
    op.drop_column('env', 'person_in_charge')
    # ### end Alembic commands ###
