"""upgrade db by adding mdb_type to table mdb

Revision ID: b6f7320709a8
Revises: 2666ea9618d7
Create Date: 2018-06-13 11:38:25.109055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f7320709a8'
down_revision = '2666ea9618d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mdb', sa.Column('mdb_type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mdb', 'mdb_type')
    # ### end Alembic commands ###
