"""empty message

Revision ID: d2f7e2f7fbb4
Revises: b6f7320709a8
Create Date: 2018-06-13 11:47:33.327411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f7e2f7fbb4'
down_revision = 'b6f7320709a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mdb', sa.Column('mdb_port', sa.String(length=128), nullable=True))
    op.add_column('mdb', sa.Column('mdb_psd', sa.String(length=128), nullable=True))
    op.add_column('mdb', sa.Column('mdb_user', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mdb', 'mdb_user')
    op.drop_column('mdb', 'mdb_psd')
    op.drop_column('mdb', 'mdb_port')
    # ### end Alembic commands ###
